// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slcrcxnqryxnnekougwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsY3JjeG5xcnl4bm5la291Z3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDUwNDQsImV4cCI6MjA3MzAyMTA0NH0.TPxTDPy1qJyQATVh5mk0a_YucbLcBHkVu16-v8IcJ5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});